# conda env create -f conda_environment.yml
name: yoloenv
channels:
  - conda-forge
  - defaults
dependencies:
  - requests
  - python-dotenv
  - pytorch
  - torchvision 
  - torchaudio
  - cudatoolkit=10.2 
  - tqdm

